<?php

namespace AppBundle\Entity\Repository;

/**
 * SeesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListBrowserWithSum()
    {

        $data = $this->createQueryBuilder('b')
            ->select('b.browser, COUNT(b.id) AS mycount')
            ->where('b.browser IS NOT NULL')
            ->orderBy('mycount', 'DESC')
            ->groupBy('b.browser')
            ->getQuery()
            ->getArrayResult();

        return $data;

    }
}
